### ISSUE TITLE
[newbie question] How does editorRefreshScreen work?

### ISSUE THREAD

**Issue by leemalmac** [antirez/kilo#32]
Hi. Awesome project!
I always wanted to learn, how does textminal/text magic work, and this code is fantastic. But I can't understand the `editorRefreshScreen` function. How doest it render text and doesn't just append it to terminal? What is the idea behind it?

Can someone give me a hint?

**Comment by skx** [comment]
As you say the routine builds up a big long string, then prints it to the console.

The magic comes from the escape codes, which are interpreted by your terminal.

As a simple example run these two commands:

     $ echo -e "\e[31mHello \e[32mWorld\e[0m"
     $ echo -e "\e[1;31;42m Yes it is awful \e[0mback to normal"

For the rest you'll need to [consult this list](http://ascii-table.com/ansi-escape-sequences-vt-100.php) - but if you work through what `kilo` is doing it's pretty good:

* resets the cursor to 0,0
* draws each line.
    * Setting colour where appropriate.
* draws the cursor.

**Comment by leemalmac** [comment]
Thank you! Now it makes sense.

**Comment by skx** [comment]
Glad I could be useful!

Asking questions is good, but probably best to close this now you're clearer :)
