### ISSUE TITLE
Why does it work

### ISSUE THREAD

**Issue by ghost** [antirez/kilo#57]
I get an error when kilo is compiled, but why does it work. Why is that?
The compiler I are using is Clang

**Comment by kgashok** [comment]
What is the error you get?

**Comment by snkprdhn** [comment]
cc -o kilo kilo.c -Wall -W -pedantic -std=c99
In file included from /usr/include/termios.h:25:0,
                 from kilo.c:40:
/usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
kilo.c: In function ‘editorRefreshScreen’:
kilo.c:953:19: warning: implicit declaration of function ‘time’; did you mean ‘tee’? [-Wimplicit-function-declaration]
     if (msglen && time(NULL)-E.statusmsg_time < 5)
                   ^~~~

**Comment by antirez** [comment]
This is just a compiler "warning". Not an error, but something the compiler warns you about, even if it is actually able to produce a binary. Btw this problem is now resolved.
